name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode keystore and create jks
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Generate keystore.properties file
        run: |
          cat <<EOF > keystore.properties
          storeFile: keystore.jks
          storePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CardNest
          path: app/build/outputs/apk/release/app-release.apk

      - name: Build AAB
        run: ./gradlew bundleRelease --stacktrace

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: CardNest
          path: app/build/outputs/bundle/release/app-release.aab
